spring:
  application:
    name: test
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env: test
girl:
  name: lfq
  age: 25
